### ISSUE TITLE
React.createRef() not working with ReCaptcha component

### ISSUE THREAD

**Issue by lifeiscontent** [codeep/react-recaptcha-google#3]
Hi, I'm trying to use the new React.createRef() API and it seems to be blowing up when using it.

specifically when I call execute on the ref.

**Comment by lifeiscontent** [comment]
it also seems this code is a bit outdated with react best practices, if I wrote a PR with the fixes would you consider them?

**Comment by lifeiscontent** [comment]
@codeep

**Comment by lifeiscontent** [comment]
@cedricwalter @styopdev

**Comment by styopdev** [comment]
Hi @lifeiscontent, Your contribution is welcome ;) just address your questions to @narek118

**Comment by lifeiscontent** [comment]
@narek118 what does `onloadCallbackName` do? I can't find it documented anywhere on the recaptcha docs anywhere. Can you point me in the right direction if this has some kind of functionality?
