### ISSUE TITLE
grecaptcha.render is not a function error

### ISSUE THREAD

**Issue by chrisshaddad** [codeep/react-recaptcha-google#7]
I'm calling `loadReCaptcha` on my App.js component's `componentDidMount`
If I go to the page that I'm using the recaptcha at after starting my app, everything is working fine.

But if i go directly to that page with my react router an error occurs, I'm guessing loadReCaptcha didn't finish loading and grecaptcha was called before it loaded

Please let me know if you need any additional info

And one more question, do you guys have any plans on updating your documentation? 

Here's how I'm rendering it:
```jsx
<ReCaptcha
  ref={el => {
    this.captcha= el;
  }}
  size="normal"
  render="explicit"
  sitekey={"Key"}
  onloadCallback={this.onLoadRecaptcha}
  verifyCallback={this.verifyCallback}
  expiredCallback={this.clearRecaptchaToken}
/>
```

**Comment by chrisshaddad** [comment]
Also your `isReady()` function in `ReCaptcha.js` is checking against the string `"undefined"` and not the actual type

**Comment by thomaskleiven** [comment]
Any updates on this?

**Comment by chrisshaddad** [comment]
@thomaskleiven a workaround you can do is check for `window.grecaptcha` before rendering the `ReCaptcha` component


```jsx
{
    window.grecaptcha ? <ReCaptcha/> : null
}
```

**Comment by thomaskleiven** [comment]
Thanks for the response.

**Comment by niquepa** [comment]
@chrisshaddad are you including the ReCaptcha script in the index.html? I was having the same Issue and was due to that, I was calling `loadReCaptcha` on `App.jsx` and including `<script src='https://www.google.com/recaptcha/api.js'></script>` too , once I removed the script I haven't the issue anymore

**Comment by chrisshaddad** [comment]
No I don't have the ReCaptcha script in index.html

**Comment by vascojm82** [comment]
I'm putting `<ReCaptcha />` inside a redux-form `<Field />` component and I'm getting the same error when re-loading the page, **"grecaptcha.render is not a function"**.  It loads fine the first time and once you click on the reCaptcha button and it starts showing you tiles of images to click, while that is happening, it times out, **"Uncaught (in promise) Timeout"**, and once you click verify (having chosen all the right images) it won't change the recaptcha image to passed or success, it goes back to an empty text box:

![image](https://user-images.githubusercontent.com/18554186/53443848-99f2f100-39da-11e9-904b-7337400266e5.png)

Has anybody encountered this specific scenario or something similar?.

**Comment by bautistaaa** [comment]
looks like the resolution was merged here e118fa5670fa268426969323b2e7fe77698376ba but its not published to npm. My version `1.1.1` still only has this check 

```
var isReady = function isReady() {
    return typeof window !== 'undefined' && typeof window.grecaptcha !== 'undefined';
};
```

can we push that so I dont have to fork?

**Comment by leskat47** [comment]
Is there a timeframe for when this might be published?

**Comment by azizali** [comment]
Yes please, I would like this fixed too.

**Comment by azizali** [comment]
Okay folks, I spent 2 hours, and I have figured out a few things.

1) Firstly, that the github version of the code is far different than the npm version of the code.
2) The name of the props that the Component receive, has also changed.

For instance `onloadCallback`is now called `onLoad` and `verifyCallback`is called `onSuccess`
don't take my word for it, checkout the source code here
https://github.com/codeep/react-recaptcha-google/blob/master/src/ReCaptcha.js#L93-L94

Okay so what is the fix today.

I forked this repo `https://github.com/azizali/react-recaptcha-google`
and I am directly installing this library via github and NOT npm.
In my package.json I have this:
```
  "dependencies": {
   ...
    "react-recaptcha-google": "https://github.com/azizali/react-recaptcha-google.git",
   ...
  }
```

Yes this is possible, for those who didn't know, as long as the `dist` files are committed to git, which are in our case.

So enjoy this solution:
Import this library directly from git like I did above
use the new prop names, `onLoad` and `onSuccess`

Hope that works for you.

**Comment by azizali** [comment]
Maintainers of this library, if you allow me, I can help out to document this. and mark the correct versions and publish it as well.

**Comment by mindtonic** [comment]
+1

**Comment by thamizhchelvan** [comment]
+1

**Comment by horaciogithub** [comment]
I had the same issue and replace this library by this one [https://www.npmjs.com/package/@blacklane/react-recaptcha-google](https://www.npmjs.com/package/@blacklane/react-recaptcha-google)
After doing some checks It seems to work perfectly.
