### ISSUE TITLE
no function called on timeout

### ISSUE THREAD

**Issue by Seanmclem** [codeep/react-recaptcha-google#9]
If my reCaptcha is validated, and then later times-out -there doesn't seem to be a function to call on timeout to update my stored token so I can control my validation. Am I missing something? Otherwise this might be a bug.
There's an onError attribute in one of the example files, but when I try it nothing happens. Also, the rest of the attributes in that example don't match the readme either

After looking into the src I see there is also an onExpired prop I can use, and that function doesn't seem to launch my function either on-expiration.

**Comment by chrisshaddad** [comment]
It seems there are a bunch of files on the github repo that are out of date, including the documentation.

If you read the files of the react-recaptcha-google library in your node modules folder they are more up to date, and they include the timeout callback which is called `expiredCallback` and not `onError`
